package autonoma.hospital.views;

import autonoma.hospital.models.Hospital;
import autonoma.hospital.models.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel Esteban Herrera Bedoya & Alejandra Zapata Castañeda
 * @version 1.0.0
 * @since 2024-04-17
 */
public class AgregarPaciente extends javax.swing.JDialog
{
    private Hospital hospital;
    private VentanaPrincipal ventanaPrincipal;
    ArrayList<Paciente> pacientes;
    
    
    public AgregarPaciente(java.awt.Frame parent, boolean modal, Hospital hospital, VentanaPrincipal ventanaPrincipal)
    {
        super(parent, modal);
        initComponents();
        this.hospital=hospital;
        this.ventanaPrincipal=ventanaPrincipal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoAgregarPaciente = new javax.swing.JPanel();
        fondoTituloAgregarPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolverAddPaciente = new javax.swing.JButton();
        inputNumeroDocumentoPaciente = new javax.swing.JTextField();
        inputNombrePaciente = new javax.swing.JTextField();
        inputEdadPaciente = new javax.swing.JTextField();
        inputTelefonoPaciente = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        NumeroDocumento = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        SalarioBase = new javax.swing.JLabel();
        SalarioBase1 = new javax.swing.JLabel();
        inputCorreoPaciente = new javax.swing.JTextField();
        btnAgregarPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fondoAgregarPaciente.setBackground(new java.awt.Color(204, 204, 204));

        fondoTituloAgregarPaciente.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR PACIENTE");

        javax.swing.GroupLayout fondoTituloAgregarPacienteLayout = new javax.swing.GroupLayout(fondoTituloAgregarPaciente);
        fondoTituloAgregarPaciente.setLayout(fondoTituloAgregarPacienteLayout);
        fondoTituloAgregarPacienteLayout.setHorizontalGroup(
            fondoTituloAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloAgregarPacienteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoTituloAgregarPacienteLayout.setVerticalGroup(
            fondoTituloAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloAgregarPacienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnVolverAddPaciente.setBackground(new java.awt.Color(255, 0, 0));
        btnVolverAddPaciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverAddPaciente.setText("<- VOLVER ");
        btnVolverAddPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        btnVolverAddPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAddPacienteMouseClicked(evt);
            }
        });

        Nombre.setText("NOMBRE");

        NumeroDocumento.setText("NUMERO DOCUMENTO");

        Edad.setText("TELÉFONO");

        SalarioBase.setText("EDAD");

        SalarioBase1.setText("CORREO");

        btnAgregarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPacienteMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospital/images/Paciente50.png"))); // NOI18N
        jLabel2.setText("GUARDAR");

        javax.swing.GroupLayout btnAgregarPacienteLayout = new javax.swing.GroupLayout(btnAgregarPaciente);
        btnAgregarPaciente.setLayout(btnAgregarPacienteLayout);
        btnAgregarPacienteLayout.setHorizontalGroup(
            btnAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarPacienteLayout.setVerticalGroup(
            btnAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout fondoAgregarPacienteLayout = new javax.swing.GroupLayout(fondoAgregarPaciente);
        fondoAgregarPaciente.setLayout(fondoAgregarPacienteLayout);
        fondoAgregarPacienteLayout.setHorizontalGroup(
            fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoTituloAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                        .addComponent(Edad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoAgregarPacienteLayout.createSequentialGroup()
                        .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnAgregarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolverAddPaciente))
                            .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                                .addComponent(SalarioBase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                                .addComponent(SalarioBase1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(inputCorreoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
            .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NumeroDocumento)
                        .addComponent(Nombre))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputNombrePaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputNumeroDocumentoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputTelefonoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)))
        );
        fondoAgregarPacienteLayout.setVerticalGroup(
            fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                .addComponent(fondoTituloAgregarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(Edad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalarioBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalarioBase1)
                    .addComponent(inputCorreoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnVolverAddPaciente))
                    .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoAgregarPacienteLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nombre))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(fondoAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputNumeroDocumentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumeroDocumento))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(inputTelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAddPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAddPacienteMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVolverAddPacienteMouseClicked

    
    private void btnAgregarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPacienteMouseClicked
        String nombre = this.inputNombrePaciente.getText();
        try
        {
            String numeroDocumentoPaciente =this.inputNumeroDocumentoPaciente.getText();
            String telefonoPaciente = this.inputTelefonoPaciente.getText();
            String edadPaciente = this.inputEdadPaciente.getText();
            String correoPaciente = this.inputCorreoPaciente.getText();
            
            Paciente paciente = new Paciente(nombre, numeroDocumentoPaciente, telefonoPaciente, Integer.parseInt(edadPaciente), correoPaciente);
            if(this.hospital.agregarPaciente(paciente))
            {
                JOptionPane.showMessageDialog(this, "El paciente "+nombre+" ha sido agregado exitosamente");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
                this.dispose();
            }
            pacientes= hospital.obtenerListaPacientes();
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número en el campo precio");
            this.inputNumeroDocumentoPaciente.setText("");
            this.inputTelefonoPaciente.setText("");
            this.inputEdadPaciente.setText("");
            this.inputCorreoPaciente.setText("");
        }
    }//GEN-LAST:event_btnAgregarPacienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NumeroDocumento;
    private javax.swing.JLabel SalarioBase;
    private javax.swing.JLabel SalarioBase1;
    private javax.swing.JPanel btnAgregarPaciente;
    private javax.swing.JButton btnVolverAddPaciente;
    private javax.swing.JPanel fondoAgregarPaciente;
    private javax.swing.JPanel fondoTituloAgregarPaciente;
    private javax.swing.JTextField inputCorreoPaciente;
    private javax.swing.JTextField inputEdadPaciente;
    private javax.swing.JTextField inputNombrePaciente;
    private javax.swing.JTextField inputNumeroDocumentoPaciente;
    private javax.swing.JTextField inputTelefonoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
