package autonoma.hospital.views;

import autonoma.hospital.models.Hospital;

/**
 *
 * @author Samuel Esteban Herrera Bedoya & Alejandra Zapata Castañeda
 * @version 1.0.0
 * @since 2024-04-13
 */
public class GestionInventario extends javax.swing.JDialog
{
    private Hospital hospital;
    private VentanaPrincipal ventanaPricipal;
    public GestionInventario(java.awt.Frame parent, boolean modal, Hospital hospital, VentanaPrincipal ventanaPrincipal)
    {
        super(parent, modal);
        initComponents();
        this.hospital=hospital;
        this.ventanaPricipal=ventanaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoFarmacia = new javax.swing.JPanel();
        fondoTituloFarmacia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tablaMedicamentos = new javax.swing.JTable();
        btnVolverFarmacia = new javax.swing.JButton();
        btnActualizarMedicamento = new javax.swing.JButton();
        btnAgregarMedicamentoMarca = new javax.swing.JButton();
        btnAgregarMedicamentoGenerico = new javax.swing.JButton();
        btnEliminarMedicamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fondoFarmacia.setBackground(new java.awt.Color(204, 204, 204));

        fondoTituloFarmacia.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FARMACIA");

        javax.swing.GroupLayout fondoTituloFarmaciaLayout = new javax.swing.GroupLayout(fondoTituloFarmacia);
        fondoTituloFarmacia.setLayout(fondoTituloFarmaciaLayout);
        fondoTituloFarmaciaLayout.setHorizontalGroup(
            fondoTituloFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloFarmaciaLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoTituloFarmaciaLayout.setVerticalGroup(
            fondoTituloFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloFarmaciaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tablaMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicamentos.getTableHeader().setReorderingAllowed(false);

        btnVolverFarmacia.setBackground(new java.awt.Color(255, 0, 0));
        btnVolverFarmacia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverFarmacia.setText("<- VOLVER ");
        btnVolverFarmacia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        btnVolverFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverFarmaciaMouseClicked(evt);
            }
        });
        btnVolverFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverFarmaciaActionPerformed(evt);
            }
        });

        btnActualizarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospital/images/editar16.png"))); // NOI18N
        btnActualizarMedicamento.setText("Actualizar");
        btnActualizarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMedicamentoMouseClicked(evt);
            }
        });

        btnAgregarMedicamentoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospital/images/MedicamentoMarca16.png"))); // NOI18N
        btnAgregarMedicamentoMarca.setText("Agregar");
        btnAgregarMedicamentoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMedicamentoMarcaMouseClicked(evt);
            }
        });
        btnAgregarMedicamentoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicamentoMarcaActionPerformed(evt);
            }
        });

        btnAgregarMedicamentoGenerico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospital/images/MedicamentoGenerico16.png"))); // NOI18N
        btnAgregarMedicamentoGenerico.setText("Agregar");
        btnAgregarMedicamentoGenerico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMedicamentoGenericoMouseClicked(evt);
            }
        });

        btnEliminarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospital/images/Cancel.png"))); // NOI18N
        btnEliminarMedicamento.setText("Eliminar");
        btnEliminarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoFarmaciaLayout = new javax.swing.GroupLayout(fondoFarmacia);
        fondoFarmacia.setLayout(fondoFarmaciaLayout);
        fondoFarmaciaLayout.setHorizontalGroup(
            fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoTituloFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoFarmaciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(fondoFarmaciaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregarMedicamentoMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarMedicamento))
                .addGap(18, 18, 18)
                .addGroup(fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarMedicamentoGenerico))
                .addGap(56, 56, 56)
                .addComponent(btnVolverFarmacia)
                .addContainerGap(813, Short.MAX_VALUE))
        );
        fondoFarmaciaLayout.setVerticalGroup(
            fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoFarmaciaLayout.createSequentialGroup()
                .addGroup(fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoFarmaciaLayout.createSequentialGroup()
                        .addComponent(fondoTituloFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tablaMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarMedicamentoGenerico)
                            .addComponent(btnAgregarMedicamentoMarca))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoFarmaciaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolverFarmacia)
                        .addGap(2, 2, 2)))
                .addGroup(fondoFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMedicamento)
                    .addComponent(btnActualizarMedicamento))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverFarmaciaActionPerformed

    private void btnVolverFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFarmaciaMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVolverFarmaciaMouseClicked

    private void btnAgregarMedicamentoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMedicamentoMarcaActionPerformed

    private void btnEliminarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMedicamentoActionPerformed

    private void btnAgregarMedicamentoMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoMarcaMouseClicked
        AgregarMedicamentoMarca vAgregarMedicamentoMarca = new AgregarMedicamentoMarca(ventanaPricipal, rootPaneCheckingEnabled);
        vAgregarMedicamentoMarca.setVisible(true);
    }//GEN-LAST:event_btnAgregarMedicamentoMarcaMouseClicked

    private void btnAgregarMedicamentoGenericoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoGenericoMouseClicked
        AgregarMedicamentoGenerico vAgregarMedicamentoGenerico = new AgregarMedicamentoGenerico(ventanaPricipal, rootPaneCheckingEnabled);
        vAgregarMedicamentoGenerico.setVisible(true);
    }//GEN-LAST:event_btnAgregarMedicamentoGenericoMouseClicked

    private void btnActualizarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMedicamentoMouseClicked
        int filaSeleccionada = tablaMedicamentos.getSelectedRow();
    
        if (filaSeleccionada != -1)
        {
            String tipoTrabajador = (String) tablaMedicamentos.getValueAt(filaSeleccionada, 2);
            if ("Generico".equals(tipoTrabajador))
            {
                ActualizarMedicamentoGenerico vActualizarMedicamentoGenerico = new ActualizarMedicamentoGenerico(ventanaPricipal, rootPaneCheckingEnabled);
                vActualizarMedicamentoGenerico.setVisible(true);
            } else if ("Marca".equals(tipoTrabajador)){
                ActualizarMedicamentoMarca vActualizarMedicamentoMarca = new ActualizarMedicamentoMarca(ventanaPricipal, rootPaneCheckingEnabled);
                vActualizarMedicamentoMarca.setVisible(true);
            } else {
                System.out.println("Tipo de trabajador desconocido: " + tipoTrabajador);
            }
        } else {
            System.out.println("No se ha seleccionado ningún trabajador.");
        }
    }//GEN-LAST:event_btnActualizarMedicamentoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMedicamento;
    private javax.swing.JButton btnAgregarMedicamentoGenerico;
    private javax.swing.JButton btnAgregarMedicamentoMarca;
    private javax.swing.JButton btnEliminarMedicamento;
    private javax.swing.JButton btnVolverFarmacia;
    private javax.swing.JPanel fondoFarmacia;
    private javax.swing.JPanel fondoTituloFarmacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tablaMedicamentos;
    // End of variables declaration//GEN-END:variables
}